apiVersion: apps/v1
kind: Deployment
metadata:
  name: carbon-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carbon-backend
  template:
    metadata:
      labels:
        app: carbon-backend
    spec:
      serviceAccountName: mltask-operator
      containers:
        - name: carbon-backend
          image: twkji/carbon-backend
          ports:
            - containerPort: 4000
          env:
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: MYSQL_DATABASE
              value: "carbonetes"
