apiVersion: v1
kind: ServiceAccount
metadata:
  name: mltask-updater
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mltask-status-editor
  namespace: default
rules:
  - apiGroups: ["ml.carbonetes.io"]
    resources:
      - mltasks
      - mltasks/status
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mltask-status-editor-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mltask-updater
    namespace: default
roleRef:
  kind: Role
  name: mltask-status-editor
  apiGroup: rbac.authorization.k8s.io
