apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: node-exporter
  namespace: monitoring
  labels:
    app: node-exporter
spec:
  type: LoadBalancer
  selector:
    app: node-exporter
  ports:
    - name: scrape
      port: 9100
      protocol: TCP
      targetPort: 9100  # <- Pod이 실제 듣는 포트