apiVersion: v1
kind: ServiceAccount
metadata:
  name: mltask-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mltask-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["*"]
  - apiGroups: ["ml.carbonetes.io"]
    resources: ["mltasks"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mltask-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mltask-operator-role
subjects:
  - kind: ServiceAccount
    name: mltask-operator
    namespace: default
