apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
        - name: dispatcher
          image: twkji/dispatcher
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: kubeconfig-volume
              mountPath: /app/configs
              readOnly: true
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-cm
                  key: MYSQL_PORT
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-password
            - name: MINIO_HOST
              valueFrom:
                configMapKeyRef:
                  name: minio-cm
                  key: MINIO_HOST
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: minio-cm
                  key: MINIO_PORT
      volumes:
        - name: kubeconfig-volume
          configMap:
            name: kubeconfig-multi
