apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  namespace: default
spec:
  selector:
    app: dispatcher
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
